"""Add completed_at

Revision ID: 683136b43f32
Revises: 063e139b895f
Create Date: 2025-04-12 17:28:11.422374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "683136b43f32"
down_revision: Union[str, None] = "063e139b895f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_id", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_todos_id", table_name="todos")
    op.drop_table("todos")
    op.drop_index("ix_categories_id", table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("ix_categories_id", "categories", ["id"], unique=False)
    op.create_table(
        "todos",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("title", sa.VARCHAR(), nullable=True),
        sa.Column("description", sa.VARCHAR(), nullable=True),
        sa.Column("priority", sa.INTEGER(), nullable=True),
        sa.Column("complete", sa.BOOLEAN(), nullable=True),
        sa.Column("owner_id", sa.INTEGER(), nullable=True),
        sa.Column("category_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_todos_id", "todos", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("email", sa.VARCHAR(), nullable=True),
        sa.Column("username", sa.VARCHAR(), nullable=True),
        sa.Column("first_name", sa.VARCHAR(), nullable=True),
        sa.Column("last_name", sa.VARCHAR(), nullable=True),
        sa.Column("hashed_password", sa.VARCHAR(), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), nullable=True),
        sa.Column("role", sa.VARCHAR(), nullable=True),
        sa.Column("phone_number", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone_number"),
        sa.UniqueConstraint("username"),
    )
    op.create_index("ix_users_id", "users", ["id"], unique=False)
    # ### end Alembic commands ###
